// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-gjXZFxv7BowSmjGxGEy10QLuljcXxLw',
    appId: '1:229247850405:web:710f8fecc646abed3ffa4c',
    messagingSenderId: '229247850405',
    projectId: 'testnew-96d14',
    authDomain: 'testnew-96d14.firebaseapp.com',
    storageBucket: 'testnew-96d14.appspot.com',
    measurementId: 'G-XJ18FCG0H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfmx6O8JTR5Vj9JM8j5QAKwkjE6Peo1w4',
    appId: '1:229247850405:android:1fbce84be51440c03ffa4c',
    messagingSenderId: '229247850405',
    projectId: 'testnew-96d14',
    storageBucket: 'testnew-96d14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Oz_2KUL7KFvulXfMxmErj_LR0NVbZhA',
    appId: '1:229247850405:ios:21b42826a9fb3a413ffa4c',
    messagingSenderId: '229247850405',
    projectId: 'testnew-96d14',
    storageBucket: 'testnew-96d14.appspot.com',
    iosClientId: '229247850405-q90pathfu2e2kcnsilbuv85brd1jo4nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Oz_2KUL7KFvulXfMxmErj_LR0NVbZhA',
    appId: '1:229247850405:ios:21b42826a9fb3a413ffa4c',
    messagingSenderId: '229247850405',
    projectId: 'testnew-96d14',
    storageBucket: 'testnew-96d14.appspot.com',
    iosClientId: '229247850405-q90pathfu2e2kcnsilbuv85brd1jo4nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytest',
  );
}
